### ISSUE TITLE
Two ways requests over Tcp Socket

### ISSUE THREAD

**Issue by ghost** [CXuesong/JsonRpc.Standard#7]
I have a server/client architecture, but I would like the server to send occasionally some messages to its client.

From what I understood JSONRPC should allow that but I wonder what is the best way to do that with your library. Once I call `StreamRpcServerHandler.Attach` I find nothing that would allow me to send request.

Is this possible?

Many thanks

**Comment by CXuesong** [comment]
You may consider also set up a `StreamRpcClientHandler` on your server, and `StreamRpcServerHandler` on your client. A JSON-RPC server and client can share the same Stream, because it can never confuse a request sent from counterparty, with a response. Actually this is how Language Server Protocol works. Both the LSP server and LSP client are, at the same time, JSON-RPC server and client.

You may take a look at the [example console application](https://github.com/CXuesong/JsonRpc.Standard/tree/master/ConsoleTestApp) for a rough idea of this.

**Comment by ghost** [comment]
Wow, thank you, I have to admit, I couldn't understand how a TcpSocket could work like this, I should have try first before asking. That's very kind of you to answer!

**Comment by CXuesong** [comment]
No problem! Just a hint, you may consider using [`NetworkStream`](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.networkstream), if applicable.

**Comment by ghost** [comment]
Yes, right now I create a `Socket` object with TCP Endoing, listen for connections, then create a `NetworkSocket` using the client connected socket and create a `NetworkStream` using this socket.
Then I create both `ByLineTextMessageReader` and `ByLineTextMessageWriter` using this stream to create the server.

I assume I'll do the same in the opposite way to have the server sending requests to client.

I hope I do it the right way, thanks for helping!

**Comment by nockawa** [comment]
Sorry, I reopen this one because we're getting unexpected behavior for two ways communication.
Here's basically what I did:

**Client Side:**
 - *Client side client to server*: Create `Socket`, `NetworkStream`, `ByLineTextMessageReader`, `ByLineTextMessageWriter`, `StreamRpcClientHandler` using both reader and writer and `JsonRpcClient` using this handler.
 - *Client side server to serve server requests*: Create `StreamRpcServerHandler` using the `ByLineTextMessageReader`, `ByLineTextMessageWriter` from above. So I'm **not** creating new instances of the reader/writer.

**Server Side:**
Pretty much the same, in the opposite direction.

I thought it was working but I now have timeout or requests sent from the server side's client to the client's server not being caught by the client's server...

I tried to create specific reader/writer instances, dedicated to both the JsonRpcServer and the JsonRpcClient but it's clearly not the way to go as nothing is working anymore...

If you could explain what I need to create on both server and client side to have two ways communication through a socket, that would be great. I didn't see unit test like this.

Your help would be greatly welcome as I need to complete this asap... many thanks.

**Comment by CXuesong** [comment]
> So I'm not creating new instances of the reader/writer.

Yes that's the inteded method of two-way communication. Reader/writer should be shared.

> If you could explain .... I didn't see unit test like this.

See the just-added [`ByLineMessagesOverSocketsTest`](https://github.com/CXuesong/JsonRpc.Standard/blob/498ece72b4ae43051ecc3513af2314aacc8ae92f/UnitTestProject1/JsonRpcStreamsTests.cs#L241). It's on TCP so I think it might help.

**Comment by nockawa** [comment]
Indeed, we got it working, I was doing the same but things seemed to be a bit odd at some point, but turned out it was fine. thank you
