### ISSUE TITLE
Question: Typical Server Loop

### ISSUE THREAD

**Issue by ghost** [CXuesong/JsonRpc.Standard#8]
I wonder if what I'm doing right now if the best/most efficient way to proceed.
I'm using TCP Socket and `NetworkStream`.

On the server side I've created a task to run the server main routine.
This routine has a while loop that breaks when the main `CancellationToken` is raised, listen for incoming socket connection.
When a client connects, I build a host, a `StreamRpcServerHandler`, then I start a new `Task` to host the server side client routine *(1)* that will creates the `NetworkStream`, `ByLineTextMessageReader`, `ByLineTextMessageWriter` and then attaches *(3)* the reader/writer to the server handler and then calls `Cancellation.WaitHandle.WaitOne()` *(2)*.

*(1)* I wonder if this is necessary to create a own task per client connecting to the server, I tried to do that in the server main routine, but didn't succeed.
*(2)* It takes a long time (aroud 3 seconds) for my client task to end when the `CancellationToken` is raised, all the time is spent in `WaitOne()`.
*(3)* I have hard time to understand the proper function and usage of the `Attach` method and especially the `IDisposable` object it returns. At some extent I'm not sure about the lifetime of the `NetworkStream` and the `Reader`/`Writer` objects. I would expect the `IDisposable` object returned during attach to control them, but I apparently failed to use it this way.

Thanks for helping

**Comment by CXuesong** [comment]
> (1) I wonder if this is necessary to create a own task per client connecting to the server, I tried to do that in the server main routine, but didn't succeed.

You may create multiple servers in the same thread/Task, but you will need to ensure to Dispose `reader`, `writer` and `IDisposable` returned from `serverHandler.Attach` when the client disconnects / server receives exit signal. In `ConsoleTestApp`, I used `CancellationToken` for sake of simplicity. For TCP connection, you may consider do the cleanup when the socket disconnects.

If you still want to use `CancellationTokenSource` as client exit signal, you may consider using [`CancellationToken.Register`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtoken.register) to register your cleanup logic without suspending the current thread. If your cleanup logic is asynchronous, consider replacing the `CancellationTokenSource` with `TaskCompletionSource<T>`.

> (2) It takes a long time (aroud 3 seconds) for my client task to end when the CancellationToken is raised, all the time is spent in WaitOne().

Do you have sample code so I can have some more context about this problem? Thanks!

> (3) I have hard time to understand the proper function and usage of the Attach method and especially the IDisposable object it returns. At some extent I'm not sure about the lifetime of the NetworkStream and the Reader/Writer objects. I would expect the IDisposable object returned during attach to control them, but I apparently failed to use it this way.

`IDisposable` returned by [`StreamRpcServerHandler.Attach`](https://cxuesong.github.io/JsonRpc.Standard/html/740b6244-688e-971b-8a20-47dd8d6b65c3.htm) only detaches `StreamRpcServerHandler` from your `MessageReader` and `MessageWriter`. That is, for example, any messages `MessageReader` pulled out from underlying stream won't be fed into `StreamRpcServerHandler`. It does nothing else.

On the other hand, you may control whether you need to prevent `NetworkStream`  from being automatically disposed with [`ByLineTextMessageWriter.LeaveWriterOpen`](https://cxuesong.github.io/JsonRpc.Standard/html/0df6ffb7-63d0-0799-f209-66487b7d6698.htm) and `ByLineTextMessageReader.LeaveReaderOpen`.

**Comment by ghost** [comment]
I will try to make a better version of my server loop based on your suggestion, I'll keep you informed. Thank you so much for your help!

**Comment by ghost** [comment]
Ok, I've managed to make the server routine not relying on tasks for client connection, works fine so far (I didn't fully tested yet).
When I stop the server, I signal a `CancellationToken` then I quit the server loop and clean up the connected client data.

You can see in the log extract below that all the time is spent inside the disposing of the Reader and Writer.
I can share code if you need.

```
18 Apr 2019 18:11:20.723 Disposing Server handler
18 Apr 2019 18:11:20.723 Disposing Reader
18 Apr 2019 18:11:22.725 Disposing Writer
18 Apr 2019 18:11:23.725 Disposing Network Stream
18 Apr 2019 18:11:23.725 Disposing Socket
18 Apr 2019 18:11:23.725  Mutex 503419d9-6171-43c5-97a2-3f74950e5a6c.2 is released for this server
```

**Comment by CXuesong** [comment]
I think there is a bug in [`Utility.TryDispose`](https://github.com/CXuesong/JsonRpc.Standard/blob/fd72c018b1bc76046abf6793c2de8e275d50e0d7/JsonRpc.Streams/Utility.cs#L45) causing semaphore not released after being taken, so the second call in [`ByLineTextMessageReader.Dispose`](https://github.com/CXuesong/JsonRpc.Standard/blob/fd72c018b1bc76046abf6793c2de8e275d50e0d7/JsonRpc.Streams/ByLineTextMessageReader.cs#L155) will get stuck for 1 sec. The same goes to the writer class.

And I've also find a potential issue with `Nerdbank.FullDuplexStream` that may cause `Dispose` called before [`ReadDirectAsync`](https://github.com/CXuesong/JsonRpc.Standard/blob/fd72c018b1bc76046abf6793c2de8e275d50e0d7/JsonRpc.Streams/ByLineTextMessageReader.cs#L106) returning, at an upper call stack, before the semaphore gets released. This will get `Dispose` stuck twice (2 sec.). I'm not sure but it seems that the reader disposal took 2 sec. Can you make sure of this? I assume you are using `NetworkStream` rather than `FullDuplexStream`, so I don't think this should happen. 
```
18 Apr 2019 18:11:20.723 Disposing Reader
18 Apr 2019 18:11:22.725 Disposing Writer
```

As a quick way for you to confirm this before I release the fix, consider replacing `ByLineTextMessageReader`/`Writer` with `PartwiseMessageReader`/`Writer` and see whether you see the same disposal issue.

**Comment by ghost** [comment]
Yup! On my basic unit test it went from 9sec down to 3!
(I had two clients, one server, so 6 reader/writer, which make sense to drop by 6sec based on what you said)

**Comment by CXuesong** [comment]
Great! Then I think fixing `TryDispose` will work. (Are you sure your code will run for 3 sec itself?)

**Comment by ghost** [comment]
Well, that's the timing of the unit test, but I didn't dig down, do you want me to take a closer look at something specific?

**Comment by CXuesong** [comment]
When thinking better of this, I don't think you will need to investigate on `PartwiseMessageReader.Dispose`, because it does not dispose `StreamReader` upon disposal, so the 3 sec. won't be caused by delay in `Dispose` method.

Actually I've introduced wait in `ByLineTextMessageReader.Dispose` because `StreamReader.Dispose` will throw exception when it is in the middle of `ReadAsync`. Waiting for a while might help `StreamReader` to complete the asynchronous operation. However, In most cases the wait shouldn't last for much time because we may seldom dispose `ByLineTextMessageReader` just when it's reading message. Perhaps I will just eliminate the wait before disposing `StreamReader`.

**Comment by CXuesong** [comment]
Released [`v0.5.0`](https://github.com/CXuesong/JsonRpc.Standard/releases/tag/v0.5.0). Note I've done some package name and namespace adjustment. You may need to change your package reference. See v0.5.0 release notes for more information.

**Comment by ghost** [comment]
Thanks, I'll test that tomorrow and will let you know!

**Comment by ghost** [comment]
So, funny thing… the `v0.5.0` fixed the wait issue on the server side, but… as long as it was only a one way communication between the server and the client.
Now that I've added a two ways communication, I still have a one second delay when disposing the `ByLineTextMessageReader` object that is now used by both a `StreamRpcServerHandler` and a `StreamRpcClientHandler`.

Basically, I've added the following lines to create a `JsonRpcClient`:
```
var clientHandler = new StreamRpcClientHandler();
_serverSideClientIDisposable = clientHandler.Attach(_reader, _writer);
_serverSideClient = new JsonRpcClient(clientHandler);```

**Comment by CXuesong** [comment]
If you are running your application in DEBUG mode, you should receive an assertion failure in this case.
https://github.com/CXuesong/JsonRpc.Standard/blob/f8fd76235f2a53102b92e03b6eab439384f26292/JsonRpc.Streams/ByLineTextMessageReader.cs#L150-L154
It means there is an ongoing `ReadAsync` operation that hasn't finished yet. You may inspect the call stack and share with me if possible.

Actually I think this function needs a rework because `StreamReader.ReadLineAsync` does not support cancellation and the function may stuck there, if there is no new line received. I think I will do so this week.

Well, it suddenly occurs to me that, perhaps you should also consinder to wrap your `NetworkStream` with `BufferedStream`. Because `NetworkStream` is a bare stream (like Console.In) and can get stuck and non-cancellable because the next packet hasn't arrived when the stream waits for the first byte. Though you may not see immediate impact on your problem until my rework is done.

**Comment by CXuesong** [comment]
I've confirmed from dotnet/corefx#24434 that we will have to wait for .NET Standard 2.1 (if there would be) before we can have cancellable `TextReader.ReadLineAsync` or other `TextReader.Read*Async` methods. I will try to multi-target `JsonRpc.Streams` to .NET Core 2.1 so I can leverage this cancellable overload as soon as possible.

https://github.com/CXuesong/JsonRpc.Standard/blob/f8fd76235f2a53102b92e03b6eab439384f26292/JsonRpc.Streams/ByLineTextMessageReader.cs#L103-L108

So now I have a question for you: Are you using .NET Core 2.1 or later versions? .NET Framework 4.8 and prior versions are not likely to support this.

**Comment by ghost** [comment]
It will be .Net core at least 2.1 on the server side, but .net framework 4.7.1 on the client side…
Client side will run under Unity Editor process.

**Comment by CXuesong** [comment]
I've released [`v0.5.1`](https://github.com/CXuesong/JsonRpc.Standard/releases/tag/v0.5.1). (Hopefully) you should not see any delay on reader thise time.

**Comment by nockawa** [comment]
I will check for that asap, right now I was struggling before of the mono bug with the PR here: https://github.com/CXuesong/JsonRpc.Standard/pull/9

I also forgot to switch to my pro account, ...

**Comment by CXuesong** [comment]
Since the advent of .NET Standard 2.1 and .NET Core 3.0, I think this issue can be closed, for now. Check out [v0.5.3](https://github.com/CXuesong/JsonRpc.Standard/releases/tag/v0.5.3)! Though there is no feature updates in this version.
